# Use official Python image as base
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install numpy

# Copy application code
COPY . /app

# Default command
CMD ["python", "9-22 assignment.py"]